M48
; DRILL file KiCad 10.0.1 date 2026-07-25T21:17:19
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-25T21:17:19+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.0551Y-3.7008
X6.0236Y-3.7008
X6.8504Y-3.622
T2
X3.2283Y-5.2756
X6.8504Y-5.2756
M30
